/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import filosofos.Cubierto;
import filosofos.Filosofo;

/**
 *
 * @author Agus
 */
public class MainWin extends javax.swing.JFrame {
    static int cant = 5;
    static Filosofo filosofos[] = new Filosofo[cant];
    static Cubierto cubiertos[] = new Cubierto[cant];
    /**
     * Creates new form MainWin
     */
    public MainWin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        comiendoF0 = new javax.swing.JLabel();
        comiendoF1 = new javax.swing.JLabel();
        comiendoF2 = new javax.swing.JLabel();
        comiendoF3 = new javax.swing.JLabel();
        comiendoF4 = new javax.swing.JLabel();
        cubierto_izq_F0 = new javax.swing.JLabel();
        cubierto_izq_F1 = new javax.swing.JLabel();
        cubierto_izq_F2 = new javax.swing.JLabel();
        cubierto_izq_F3 = new javax.swing.JLabel();
        cubierto_izq_F4 = new javax.swing.JLabel();
        cubierto_der_F4 = new javax.swing.JLabel();
        cubierto_der_F3 = new javax.swing.JLabel();
        cubierto_der_F2 = new javax.swing.JLabel();
        cubierto_der_F1 = new javax.swing.JLabel();
        cubierto_der_F0 = new javax.swing.JLabel();
        btnStart = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        mesa = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);

        comiendoF0.setText("Filosofo 0 esta comiendo.");
        jPanel2.add(comiendoF0);
        comiendoF0.setBounds(590, 80, 130, 30);

        comiendoF1.setText("Filosofo 1 esta comiendo.");
        jPanel2.add(comiendoF1);
        comiendoF1.setBounds(790, 400, 130, 30);

        comiendoF2.setText("Filosofo 2 esta comiendo.");
        jPanel2.add(comiendoF2);
        comiendoF2.setBounds(760, 670, 130, 30);

        comiendoF3.setText("Filosofo 3 esta comiendo.");
        jPanel2.add(comiendoF3);
        comiendoF3.setBounds(80, 670, 180, 30);

        comiendoF4.setText("Filosofo 4 esta comiendo.");
        jPanel2.add(comiendoF4);
        comiendoF4.setBounds(20, 340, 130, 30);

        cubierto_izq_F0.setText("Filosofo 0 tiene cubierto izquierdo.");
        jPanel2.add(cubierto_izq_F0);
        cubierto_izq_F0.setBounds(590, 110, 180, 30);

        cubierto_izq_F1.setText("Filosofo 1 tiene cubierto izquierdo.");
        jPanel2.add(cubierto_izq_F1);
        cubierto_izq_F1.setBounds(790, 430, 180, 30);

        cubierto_izq_F2.setText("Filosofo 2 tiene cubierto izquierdo.");
        jPanel2.add(cubierto_izq_F2);
        cubierto_izq_F2.setBounds(760, 700, 180, 30);

        cubierto_izq_F3.setText("Filosofo 3 tiene cubierto izquierdo.");
        jPanel2.add(cubierto_izq_F3);
        cubierto_izq_F3.setBounds(80, 700, 180, 30);

        cubierto_izq_F4.setText("Filosofo 4 tiene cubierto izquierdo.");
        jPanel2.add(cubierto_izq_F4);
        cubierto_izq_F4.setBounds(20, 370, 180, 30);

        cubierto_der_F4.setText("Filosofo 4 tiene cubierto derecho.");
        jPanel2.add(cubierto_der_F4);
        cubierto_der_F4.setBounds(20, 400, 180, 30);

        cubierto_der_F3.setText("Filosofo 3 tiene cubierto derecho.");
        jPanel2.add(cubierto_der_F3);
        cubierto_der_F3.setBounds(80, 730, 180, 30);

        cubierto_der_F2.setText("Filosofo 2 tiene cubierto derecho.");
        jPanel2.add(cubierto_der_F2);
        cubierto_der_F2.setBounds(760, 730, 180, 30);

        cubierto_der_F1.setText("Filosofo 1 tiene cubierto derecho.");
        jPanel2.add(cubierto_der_F1);
        cubierto_der_F1.setBounds(790, 460, 180, 30);

        cubierto_der_F0.setText("Filosofo 0 tiene cubierto izquierdo.");
        jPanel2.add(cubierto_der_F0);
        cubierto_der_F0.setBounds(590, 140, 180, 30);

        btnStart.setText("Empezar");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });
        jPanel2.add(btnStart);
        btnStart.setBounds(70, 110, 140, 50);

        jLabel2.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        jLabel2.setText("Problema de los filosofos con Semaphores y Threads en Java");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 0, 900, 50);

        mesa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/src/mesa_con_cubiertos.png"))); // NOI18N
        jPanel2.add(mesa);
        mesa.setBounds(0, 0, 1000, 870);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 998, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 813, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        jPanel2.setVisible(false);
    }//GEN-LAST:event_btnStartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWin().setVisible(true);
            }
        });
        
        for (int i = 0; i < cant; i++) {
            cubiertos[i] = new Cubierto();
        }

        for (int i = 0; (i < cant); i++) {
            filosofos[i] = new Filosofo(i, cubiertos[i], cubiertos[(i + 1) % cant], (i == cant - 1));
            filosofos[i].start();
        }

        while (true) {
            try {
                Thread.sleep(1000);
            } catch (InterruptedException e) {
                e.printStackTrace(System.out);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStart;
    private javax.swing.JLabel comiendoF0;
    private javax.swing.JLabel comiendoF1;
    private javax.swing.JLabel comiendoF2;
    private javax.swing.JLabel comiendoF3;
    private javax.swing.JLabel comiendoF4;
    private javax.swing.JLabel cubierto_der_F0;
    private javax.swing.JLabel cubierto_der_F1;
    private javax.swing.JLabel cubierto_der_F2;
    private javax.swing.JLabel cubierto_der_F3;
    private javax.swing.JLabel cubierto_der_F4;
    private javax.swing.JLabel cubierto_izq_F0;
    private javax.swing.JLabel cubierto_izq_F1;
    private javax.swing.JLabel cubierto_izq_F2;
    private javax.swing.JLabel cubierto_izq_F3;
    private javax.swing.JLabel cubierto_izq_F4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel mesa;
    // End of variables declaration//GEN-END:variables
}
